{"name": "Невозможно обновить данные без авторизации", "status": "passed", "parameters": [{"name": "field", "value": "'name'"}], "start": 1742965334114, "stop": 1742965335110, "uuid": "f83e93b4-d373-467f-98bb-541ac1e9df74", "historyId": "2419109320a1266cce3693df83c2114e", "testCaseId": "50ab14e5bd59ba94665da529c21fdea1", "fullName": "tests.test_user.TestUser#test_update_unauthorized_user_data_fails", "labels": [{"name": "feature", "value": "Пользователь"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-QVE1U26H"}, {"name": "thread", "value": "13432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}